### PR TITLE
adding customizeTheme method

### PR DESCRIPTION
**Pull request by machadogj**
Before doing `lock.show()` I do something like:
````
  lock.customizeTheme({
    A0ThemePrimaryButtonNormalColor: "#009DEB",
    A0ThemePrimaryButtonFont: font,
    A0ThemeSecondaryButtonTextColor: "#ffffff",
    A0ThemeSecondaryButtonFont: font,
    A0ThemeTextFieldTextColor: "#ffffff",
    A0ThemeTextFieldPlaceholderTextColor: "#ffffff",
    A0ThemeTextFieldIconColor: "#ffffff",
    A0ThemeTextFieldFont: font,
    A0ThemeTitleTextColor: "#ffffff",
    A0ThemeTitleFont: font,
    A0ThemeDescriptionTextColor: "#ffffff",
    A0ThemeDescriptionFont: font,
    A0ThemeSeparatorTextColor: "#ffffff",
    A0ThemeSeparatorTextFont: font,
    A0ThemeScreenBackgroundImageName: "backgroundImage",
    A0ThemeIconImageName: "papaLogo",
    A0ThemeCredentialBoxBorderColor: "", //transparent
  });
````
Works for me, hope it helps!

### CODE REVIEW

**Comment by hzalaz** [comment]
@machadogj Thanks for the PR. I think we should not use the constant values since they are meant to be used in objc using the static const variable directly without checking the value so it we change the value it will break this (Also I am planning to change the values). 

Since it's js I was thinking of passing to show (or in Auth0Lock constructor function) the theme to use as a js object much like styles in react. If you are up to it, feel free to submit a pr or update this one

**Comment by jhabdas** [comment]
@hzalaz Would you consider creating a branch in this repo with these changes to [prevent further forks](https://github.com/futurice/pepperoni-app-kit/issues/71)? While I understand customization in this manner isn't something you'd prefer not having it is resulting in popular libraries creating forks and getting behind as shown in the linked above. Thoughts?

**Comment by hzalaz** [comment]
@jhabdas it's not that I am against of adding that functionality but because of the way it was implemented by relying in implementation details (a constant value). I am willing to merge a PR that abstract how it's implemented, I'd do it myself but we are working on a new version of Lock (iOS/Android) so I have no time to add features, only bug fixing.

What I'd expect is something like this

```js
lock.show({
  style: {
    title: {
      color: '#000000',
      font: myfont
    },
    icon { imageName: 'mylogo' }
  }
}, (err, profile, token) => ...);
```

My only concern are the images that have to be bundled by Xcode and not by RN package but a console log can be added to warn if that's not the case.

**Comment by jhabdas** [comment]
Cool. Thanks for the info. Very cool product. Keep up the speed. Code is documentation. ;)

**Comment by Msspl-KrishnenduBhattacharyya** [comment]
@hzalaz thank you for this package. When we will get the new package with custom theme? And one more thing, if we can add the custom structure also it will be great for us & future use ( Like two tab signin, signup)

**Pull request closed without merging**
