### PR TITLE
fixes for rn 40

### PR DESCRIPTION
**Pull request by chirag04**
@hzalaz RN 40 has a breaking change regarding how react is imported.

### CODE REVIEW

**Comment by chirag04** [comment]
This would need a major version bump.

**Comment by hzalaz** [comment]
@chirag04 tried in 0.41 without this and still works

**Comment by chirag04** [comment]
true. works for me as well but i'm not sure y its working. refer: https://github.com/facebook/react-native/releases/tag/v0.40.0

**Comment by duhseekoh** [comment]
So what version of this library works for React Native < 0.40 ? The latest only works with >= 0.40. Would be nice to have a compatibility table in the readme.

**Pull request closed without merging**
