### PR TITLE
Added options for disable signup and reset password button

### PR DESCRIPTION
**Pull request by deepaksisodiya**
Also update the readme file
Now disable signup and reset password button like

```
lock.show({
      disableSignUp: true,
      disableResetPassword: true
});
```

### CODE REVIEW

**Comment by bartolkaruza** [comment]
This is for iOS only, could this work for Android as well?

**Comment by hzalaz** [comment]
@deepaksisodiya can you update your branch with latest changes from master? I'll merge it then

**Comment by deepaksisodiya** [comment]
@hzalaz updated the PR with the latest changes from master

**Comment by hzalaz** [comment]
Thanks @deepaksisodiya

**Pull request merged**
